exclude: "^pages/atomic-red-team/atomics"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.1.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.5.3"]
  - repo: https://github.com/google/yamlfmt
    rev: "v0.11.0"
    hooks:
      - id: yamlfmt
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3' # or any later Vulture version
    hooks:
      - id: vulture
