name: generate-atomics
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write
jobs:
  generate-atomics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTECTED_BRANCH_PUSH_TOKEN }}
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Generate atomics
        run: poetry run python bin/generate.py
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: update github with new site
        run: |
          git config --global user.name 'actions-bot'
          git config --global user.email 'username@users.noreply.github.com'
          git config --global push.default simple
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated update" && git push origin $GITHUB_REF_NAME -f
