name: Code quality
on:
  pull_request:
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
